// -----------------------------------------------------------------------------------------------------------------
// <copyright file="StringCheckToVisibilityConverterTests.cs" company="dwndland">
//     Copyright (c) David Wendland. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------------------------------------------------

using System;
using System.Windows;
using NUnit.Framework;

// ReSharper disable once CheckNamespace

namespace Chapter.Net.WPF.Converters.Tests;

public class StringCheckToVisibilityConverterTests : SingleAndMultiValueConverterTester<StringCheckToVisibilityConverter>
{
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, 0, null, Visibility.Visible)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Collapsed, Visibility.Collapsed, 0, null, Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Hidden, Visibility.Collapsed, 0, null, Visibility.Hidden)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, 0, "", Visibility.Visible)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Collapsed, Visibility.Collapsed, 0, "", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Hidden, Visibility.Collapsed, 0, "", Visibility.Hidden)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, 0, "  ", Visibility.Visible)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Collapsed, Visibility.Collapsed, 0, "  ", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Hidden, Visibility.Collapsed, 0, "  ", Visibility.Hidden)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, 0, "a", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Visible, 0, "a", Visibility.Visible)]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Hidden, 0, "a", Visibility.Hidden)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, 0, null, Visibility.Visible)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Collapsed, Visibility.Collapsed, 0, null, Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Hidden, Visibility.Collapsed, 0, null, Visibility.Hidden)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, 0, "", Visibility.Visible)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Collapsed, Visibility.Collapsed, 0, "", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Hidden, Visibility.Collapsed, 0, "", Visibility.Hidden)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, 0, "  ", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Visible, 0, "  ", Visibility.Visible)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Hidden, 0, "  ", Visibility.Hidden)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, 0, "a", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Visible, 0, "a", Visibility.Visible)]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Hidden, 0, "a", Visibility.Hidden)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, 0, null, Visibility.Visible)]
    [TestCase(StringCheckType.IsNull, Visibility.Collapsed, Visibility.Collapsed, 0, null, Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNull, Visibility.Hidden, Visibility.Collapsed, 0, null, Visibility.Hidden)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, 0, "", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Visible, 0, "", Visibility.Visible)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Hidden, 0, "", Visibility.Hidden)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, 0, "  ", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Visible, 0, "  ", Visibility.Visible)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Hidden, 0, "  ", Visibility.Hidden)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, 0, "a", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Visible, 0, "a", Visibility.Visible)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Hidden, 0, "a", Visibility.Hidden)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, 0, Visibility.Hidden, Visibility.Collapsed)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Visible, 0, Visibility.Hidden, Visibility.Visible)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Hidden, 0, Visibility.Hidden, Visibility.Hidden)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, 0, "", Visibility.Visible)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Collapsed, Visibility.Collapsed, 0, "", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Hidden, Visibility.Collapsed, 0, "", Visibility.Hidden)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, 0, "  ", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Visible, 0, "  ", Visibility.Visible)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Hidden, 0, "  ", Visibility.Hidden)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, 0, "a", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Visible, 0, "a", Visibility.Visible)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Hidden, 0, "a", Visibility.Hidden)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, 0, Visibility.Hidden, Visibility.Collapsed)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Visible, 0, Visibility.Hidden, Visibility.Visible)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Hidden, 0, Visibility.Hidden, Visibility.Hidden)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, 0, "", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Visible, 0, "", Visibility.Visible)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Hidden, 0, "", Visibility.Hidden)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, 0, "  ", Visibility.Visible)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Collapsed, Visibility.Collapsed, 0, "  ", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Hidden, Visibility.Collapsed, 0, "  ", Visibility.Hidden)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, 0, "a", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Visible, 0, "a", Visibility.Visible)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Hidden, 0, "a", Visibility.Hidden)]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Collapsed, 0, "a", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Visible, 0, "a", Visibility.Visible)]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Hidden, 0, "a", Visibility.Hidden)]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Collapsed, 0, "A", Visibility.Visible)]
    [TestCase(StringCheckType.IsUpper, Visibility.Collapsed, Visibility.Collapsed, 0, "A", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsUpper, Visibility.Hidden, Visibility.Collapsed, 0, "A", Visibility.Hidden)]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Collapsed, 0, "a", Visibility.Visible)]
    [TestCase(StringCheckType.IsLower, Visibility.Collapsed, Visibility.Collapsed, 0, "a", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsLower, Visibility.Hidden, Visibility.Collapsed, 0, "a", Visibility.Hidden)]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Collapsed, 0, "A", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Visible, 0, "A", Visibility.Visible)]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Hidden, 0, "A", Visibility.Hidden)]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Collapsed, 4, "aaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Collapsed, Visibility.Collapsed, 4, "aaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Hidden, Visibility.Collapsed, 4, "aaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Collapsed, 4, "aaaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Visible, 4, "aaaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Hidden, 4, "aaaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, 4, "aaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Collapsed, Visibility.Collapsed, 4, "aaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Hidden, Visibility.Collapsed, 4, "aaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, 4, "aaaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Collapsed, Visibility.Collapsed, 4, "aaaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Hidden, Visibility.Collapsed, 4, "aaaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, 4, "aaaaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Visible, 4, "aaaaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Hidden, 4, "aaaaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Collapsed, 4, "aaaaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Collapsed, Visibility.Collapsed, 4, "aaaaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Hidden, Visibility.Collapsed, 4, "aaaaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Collapsed, 4, "aaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Visible, 4, "aaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Hidden, 4, "aaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, 4, "aaaaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Collapsed, Visibility.Collapsed, 4, "aaaaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Hidden, Visibility.Collapsed, 4, "aaaaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, 4, "aaaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Collapsed, Visibility.Collapsed, 4, "aaaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Hidden, Visibility.Collapsed, 4, "aaaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, 4, "aaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Visible, 4, "aaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Hidden, 4, "aaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Collapsed, 4, "aaaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsExactLength, Visibility.Collapsed, Visibility.Collapsed, 4, "aaaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsExactLength, Visibility.Hidden, Visibility.Collapsed, 4, "aaaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Collapsed, 4, "aaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Visible, 4, "aaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Hidden, 4, "aaa", Visibility.Hidden)]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Collapsed, 4, "aaaaa", Visibility.Collapsed)]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Visible, 4, "aaaaa", Visibility.Visible)]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Hidden, 4, "aaaaa", Visibility.Hidden)]
    public void Convert_Called_Converts(StringCheckType checkType, Visibility trueIs, Visibility falseIs, int variable, object input, Visibility expectation)
    {
        _target.CheckType = checkType;
        _target.TrueIs = trueIs;
        _target.FalseIs = falseIs;
        _target.Variable = variable;

        Convert(input, expectation);
    }

    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, null, "", "")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, null, "", "")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, null, "", "")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, "", " ", " ")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "", " ", " ")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "", " ", " ")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "a", "a", "a")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "a", "a", "a")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "a", "a", "a")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "a", "", "")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 0, Visibility.Visible, "a", "", "")]
    [TestCase(StringCheckType.IsNullOrWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 0, Visibility.Collapsed, "a", "", "")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, null, "", "")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, null, "", "")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, null, "", "")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, "", "", "")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "", "", "")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "", "", "")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "a", "a", "a")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "a", "a", "a")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "a", "a", "a")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "a", "", "")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 0, Visibility.Visible, "a", "", "")]
    [TestCase(StringCheckType.IsNullOrEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 0, Visibility.Collapsed, "a", "", "")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, null, null, null)]
    [TestCase(StringCheckType.IsNull, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, null, null, null)]
    [TestCase(StringCheckType.IsNull, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, null, null, null)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "", "", "")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "", "", "")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "", "", "")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "a", "a", "a")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "a", "a", "a")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "a", "a", "a")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, null, "", "")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 0, Visibility.Visible, null, "", "")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 0, Visibility.Collapsed, null, "", "")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, null, null, null)]
    [TestCase(StringCheckType.IsNull, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, null, null, null)]
    [TestCase(StringCheckType.IsNull, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, null, null, null)]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "a", "a", "a")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "a", "a", "a")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "a", "a", "a")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, null, null, "")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 0, Visibility.Visible, null, null, "")]
    [TestCase(StringCheckType.IsNull, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 0, Visibility.Collapsed, null, null, "")]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, null, null, null)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, null, null, null)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, null, null, null)]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, "", "", "")]
    [TestCase(StringCheckType.IsEmpty, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "", "", "")]
    [TestCase(StringCheckType.IsEmpty, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "", "", "")]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "a", "a", "a")]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "a", "a", "a")]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "a", "a", "a")]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, null, null, "")]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 0, Visibility.Visible, null, null, "")]
    [TestCase(StringCheckType.IsEmpty, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 0, Visibility.Collapsed, null, null, "")]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, null, null, null)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, null, null, null)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, null, null, null)]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "  ", " ", "   ")]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "a", "a", "a")]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "a", "a", "a")]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "a", "a", "a")]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, null, null, "  ")]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 0, Visibility.Visible, null, null, "  ")]
    [TestCase(StringCheckType.IsWhitespace, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 0, Visibility.Collapsed, null, null, "  ")]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "a", "a", "a")]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "a", "a", "a")]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "a", "a", "a")]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, "A", "A", "A")]
    [TestCase(StringCheckType.IsUpper, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "A", "A", "A")]
    [TestCase(StringCheckType.IsUpper, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "A", "A", "A")]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "a", "a", "A")]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 0, Visibility.Visible, "a", "a", "A")]
    [TestCase(StringCheckType.IsUpper, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 0, Visibility.Collapsed, "a", "a", "A")]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "A", "A", "A")]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 0, Visibility.Visible, "A", "A", "A")]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 0, Visibility.Hidden, "A", "A", "A")]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Visible, "a", "a", "a")]
    [TestCase(StringCheckType.IsLower, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Collapsed, "a", "a", "a")]
    [TestCase(StringCheckType.IsLower, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "a", "a", "a")]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 0, Visibility.Hidden, "A", "A", "a")]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 0, Visibility.Visible, "A", "A", "a")]
    [TestCase(StringCheckType.IsLower, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 0, Visibility.Collapsed, "A", "A", "a")]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Visible, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 4, Visibility.Visible, "aaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 4, Visibility.Hidden, "aaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 4, Visibility.Visible, "aaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThan, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 4, Visibility.Collapsed, "aaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Visible, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Visible, "aaaa", "aa", "a")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaaa", "aa", "a")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaa", "aa", "a")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 4, Visibility.Visible, "aaaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 4, Visibility.Hidden, "aaaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 4, Visibility.Visible, "aaaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsShorterThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 4, Visibility.Collapsed, "aaaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Visible, "aaaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 4, Visibility.Visible, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 4, Visibility.Hidden, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 4, Visibility.Visible, "aaaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThan, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 4, Visibility.Collapsed, "aaaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Visible, "aaaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaaa", "aaaaaa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Visible, "aaaa", "aaaaa", "aaaaaa")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaaa", "aaaaa", "aaaaaa")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaa", "aaaaa", "aaaaaa")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 4, Visibility.Visible, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 4, Visibility.Hidden, "aaa", "aa", "a")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 4, Visibility.Visible, "aaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsLongerThanOrEqualTo, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 4, Visibility.Collapsed, "aaaa", "aa", "aaaaaaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Visible, "aaaa", "aaaa", "aaaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Collapsed, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaaa", "aaaa", "aaaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Hidden, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaa", "aaaa", "aaaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaa", "aaa", "aaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 4, Visibility.Visible, "aaa", "aaa", "aaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 4, Visibility.Hidden, "aaa", "aaa", "aaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Collapsed, "aaaaa", "aaaaa", "aaaaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Visible, Visibility.Hidden, 4, Visibility.Visible, "aaaaa", "aaaaa", "aaaaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Hidden, Visibility.Hidden, 4, Visibility.Hidden, "aaaaa", "aaaaa", "aaaaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Collapsed, Visibility.Hidden, 4, Visibility.Hidden, "aaaa", "aa", "aaaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Collapsed, Visibility.Visible, 4, Visibility.Visible, "aaaa", "aa", "aaaa")]
    [TestCase(StringCheckType.IsExactLength, Visibility.Visible, Visibility.Collapsed, Visibility.Collapsed, 4, Visibility.Collapsed, "aaaa", "aa", "aaaa")]
    public void MultiConvert_Called_Converts(StringCheckType checkType, Visibility trueIs, Visibility falseIs, Visibility mixedIs, int variable, Visibility expectation, params object[] input)
    {
        _target.CheckType = checkType;
        _target.TrueIs = trueIs;
        _target.FalseIs = falseIs;
        _target.MixedIs = mixedIs;
        _target.Variable = variable;

        MultiConvert(input, expectation);
    }

    [Test]
    public void ConvertBack_Called_RaisesException()
    {
        Assert.That(() => ConvertBack(Visibility.Hidden, Visibility.Hidden), Throws.TypeOf<NotImplementedException>());
    }

    [Test]
    public void MultiConvertBack_Called_RaisesException()
    {
        Assert.That(() => MultiConvertBack(Visibility.Hidden, []), Throws.TypeOf<NotImplementedException>());
    }
}